### ISSUE TITLE
Random Issues with EXOMailboxSettings

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Office365DSC#142]
### Details of the scenario you tried and the problem that is occurring
Every now and then, extracting EXOMailboxSettings with ReverseDSC will throw errors complaining about "Get-MailboxRegionalConfiguration" giving issues like following:

Error on proxy command 'Get-MailboxRegionalConfiguration -Identity:'admin'' to server
YQBPR0101MB0851.CANPRD01.PROD.OUTLOOK.COM: Server version 15.20.2052.0000, Proxy method
PSWS:
Cmdlet error with following error message:
Microsoft.Exchange.Data.Storage.MailboxInfoStaleException: Can't connect to the mailbox of
user Mailbox database guid: e350cc7b-d7cb-4416-a715-02adbe30c84c because the
ExchangePrincipal object contains outdated information. The mailbox may have been moved
recently. ---> Microsoft.Exchange.Data.Storage.DatabaseNotFoundException: The database with
ID 'e350cc7b-d7cb-4416-a715-02adbe30c84c' couldn't be found. --->
Microsoft.Exchange.Data.Directory.ServerInMMException: The domain controller
'YQBPR0101DC0005.CANPRD01.PROD.OUTLOOK.COM' is not available for use at the moment. Please
try again.
   at Microsoft.Exchange.Data.Directory.TopologyDiscovery.SuitabilityVerifier.CheckIsServerSu
itable(String fqdn, Boolean isGlobalCatalog, NetworkCredential credentials,
SuitabilityCheckResult& suitabilityCheckResult)
   at Microsoft.Exchange.Data.Directory.ConnectionPoolManager.GetConnection(ConnectionType
connectionType, String partitionFqdn, ADObjectId domain, String serverName, Int32 port,
NetworkCredential credential)
   at Microsoft.Exchange.Data.Directory.ConnectionPoolManager.GetConnection(ConnectionType
connectionType, String partitionFqdn, NetworkCredential networkCredential, String
serverName, Int32 port)
   at Microsoft.Exchange.Data.Directory.ConnectionPoolManager.GetConnection(ConnectionType
connectionType, String partitionFqdn, NetworkCredential networkCredential, String serverName)
   at Microsoft.Exchange.Data.Directory.ADDataSession.GetConnection(String preferredServer,
Boolean isWriteOperation, String optionalBaseDN, ADObjectId& rootId, ADScope scope)
   at Microsoft.Exchange.Data.Directory.ADDataSession.InternalFind[TResult](ADObjectId
rootId, String optionalBaseDN, ADObjectId readId, QueryScope scope, QueryFilter filter,
SortBy sortBy, Int32 maxResults, IEnumerable`1 properties, Boolean includeDeletedObjects,
Boolean includeSoftDeletedObjects)
   at Microsoft.Exchange.Data.Directory.ADDataSession.Find[TResult](ADObjectId rootId,
QueryScope scope, QueryFilter filter, SortBy sortBy, Int32 maxResults, IEnumerable`1
properties, Boolean includeDeletedObjects, Boolean includeSoftDeletedObjects)
   at Microsoft.Exchange.Data.Directory.SystemConfiguration.ADTopologyConfigurationSession.In
ternalFind[TResult](ADObjectId rootId, QueryScope scope, QueryFilter filter, SortBy sortBy,
Int32 maxResults, IEnumerable`1 properties)
   at Microsoft.Exchange.Data.Directory.SystemConfiguration.ADTopologyConfigurationSession.Fi
nd[TResult](ADObjectId rootId, QueryScope scope, QueryFilter filter, SortBy sortBy, Int32
maxResults, IEnumerable`1 properties, String callerFilePath, Int32 callerFileLine, String
memberName)
   at Microsoft.Exchange.Data.HA.DirectoryServices.ADTopologyConfigurationSessionWrapper.Find
Internal[TADWrapperObject,TADObject](ADObjectId rootId, QueryScope scope, QueryFilter
filter, SortBy sortBy, Int32 maxResults, IEnumerable`1 properties)
   at Microsoft.Exchange.Data.HA.DirectoryServices.ADTopologyConfigurationSessionWrapper.Find
[TADWrapperObject](ADObjectId rootId, QueryScope scope, QueryFilter filter, SortBy sortBy,
Int32 maxResults)
   at Microsoft.Exchange.Data.Storage.Cluster.DirectoryServices.SimpleAdObjectLookup`1.<>c__D
isplayClass9_0.<FindAdObjectTypeByGuidStatic>b__0()
   at Microsoft.Exchange.Data.Directory.ADNotificationAdapter.RunADOperation(ADOperation
adOperation, Int32 retryCount)
   at Microsoft.Exchange.Data.Directory.ADNotificationAdapter.TryRunADOperation(ADOperation
adOperation, Int32 retryCount)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Data.Storage.ActiveManager.ActiveManager.GetDatabaseByGuidEx(IFindAd
Object`1 databaseLookup, Guid databaseId, AdObjectLookupFlags flags, IPerformanceDataLogger
perfLogger)
   at
Microsoft.Exchange.Data.Storage.ActiveManager.ActiveManager.GetServerNameForDatabase(Guid
databaseId, GetServerForDatabaseFlags gsfdFlags, IPerformanceDataLogger perfLogger,
IADDatabase& database)
   at Microsoft.Exchange.Data.Storage.ActiveManager.ActiveManager.GetServerForDatabase(Guid
databaseId, GetServerForDatabaseFlags gsfdFlags, IPerformanceDataLogger perfLogger)
   at Microsoft.Exchange.Data.Storage.DatabaseLocationProvider.GetLocationInfo(Guid mdbGuid,
Boolean bypassCache, Boolean ignoreSiteBoundary)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Data.Storage.DatabaseLocationProvider.GetLocationInfo(Guid mdbGuid,
Boolean bypassCache, Boolean ignoreSiteBoundary)
   at Microsoft.Exchange.Data.Storage.Principal.MailboxLocationFactory.Create(Guid mdbGuid,
RemotingOptions remotingOptions, Boolean createLocationOnDemand)
   at
Microsoft.Exchange.Data.Storage.ExchangePrincipalFactory.InternalFromADUser(IGenericADUser
user, RemotingOptions remotingOptions, Boolean createLocationOnDemand)
   at Microsoft.Exchange.Data.Storage.Performance.MailboxOperationPerformanceTracker.ExecuteW
ithLatencyTracking[T](ActivityOperationType operation, Func`1 action, String instance)
   at Microsoft.Exchange.Management.StoreTasks.GetMailboxRegionalConfiguration.CreateMailboxD
ataProvider(ADUser adUser)
   at Microsoft.Exchange.Configuration.Tasks.DataAccessTask`1.InternalStateReset()
   at Microsoft.Exchange.Configuration.Tasks.GetTaskBase`1.InternalStateReset()
   at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__93_1()
   at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName,
Action func, Boolean terminatePipelineIfFailed).
[Server=YTBPR01MB3038,RequestId=8be3b4cf-e565-4ceb-850a-86292a97c7d4,TimeStamp=7/11/2019
1:29:51 AM] .
    + CategoryInfo          : NotSpecified: (:) [Get-MailboxRegionalConfiguration], CmdletPr
   oxyException
    + FullyQualifiedErrorId : Microsoft.Exchange.Configuration.CmdletProxyException,Microsof
   t.Exchange.Management.StoreTasks.GetMailboxRegionalConfiguration
    + PSComputerName        : outlook.office365.com

We still can't find a pattern for these occurrences and they are not always reproduced from one extraction run to another. Logging this for Knowledge Base purposes.

#### Verbose logs showing the problem
Error on proxy command 'Get-MailboxRegionalConfiguration -Identity:'admin'' to server
YQBPR0101MB0851.CANPRD01.PROD.OUTLOOK.COM: Server version 15.20.2052.0000, Proxy method
PSWS:
Cmdlet error with following error message:
Microsoft.Exchange.Data.Storage.MailboxInfoStaleException: Can't connect to the mailbox of
user Mailbox database guid: e350cc7b-d7cb-4416-a715-02adbe30c84c because the
ExchangePrincipal object contains outdated information. The mailbox may have been moved
recently. ---> Microsoft.Exchange.Data.Storage.DatabaseNotFoundException: The database with
ID 'e350cc7b-d7cb-4416-a715-02adbe30c84c' couldn't be found. --->
Microsoft.Exchange.Data.Directory.ServerInMMException: The domain controller
'YQBPR0101DC0005.CANPRD01.PROD.OUTLOOK.COM' is not available for use at the moment. Please
try again.
   at Microsoft.Exchange.Data.Directory.TopologyDiscovery.SuitabilityVerifier.CheckIsServerSu
itable(String fqdn, Boolean isGlobalCatalog, NetworkCredential credentials,
SuitabilityCheckResult& suitabilityCheckResult)
   at Microsoft.Exchange.Data.Directory.ConnectionPoolManager.GetConnection(ConnectionType
connectionType, String partitionFqdn, ADObjectId domain, String serverName, Int32 port,
NetworkCredential credential)
   at Microsoft.Exchange.Data.Directory.ConnectionPoolManager.GetConnection(ConnectionType
connectionType, String partitionFqdn, NetworkCredential networkCredential, String
serverName, Int32 port)
   at Microsoft.Exchange.Data.Directory.ConnectionPoolManager.GetConnection(ConnectionType
connectionType, String partitionFqdn, NetworkCredential networkCredential, String serverName)
   at Microsoft.Exchange.Data.Directory.ADDataSession.GetConnection(String preferredServer,
Boolean isWriteOperation, String optionalBaseDN, ADObjectId& rootId, ADScope scope)
   at Microsoft.Exchange.Data.Directory.ADDataSession.InternalFind[TResult](ADObjectId
rootId, String optionalBaseDN, ADObjectId readId, QueryScope scope, QueryFilter filter,
SortBy sortBy, Int32 maxResults, IEnumerable`1 properties, Boolean includeDeletedObjects,
Boolean includeSoftDeletedObjects)
   at Microsoft.Exchange.Data.Directory.ADDataSession.Find[TResult](ADObjectId rootId,
QueryScope scope, QueryFilter filter, SortBy sortBy, Int32 maxResults, IEnumerable`1
properties, Boolean includeDeletedObjects, Boolean includeSoftDeletedObjects)
   at Microsoft.Exchange.Data.Directory.SystemConfiguration.ADTopologyConfigurationSession.In
ternalFind[TResult](ADObjectId rootId, QueryScope scope, QueryFilter filter, SortBy sortBy,
Int32 maxResults, IEnumerable`1 properties)
   at Microsoft.Exchange.Data.Directory.SystemConfiguration.ADTopologyConfigurationSession.Fi
nd[TResult](ADObjectId rootId, QueryScope scope, QueryFilter filter, SortBy sortBy, Int32
maxResults, IEnumerable`1 properties, String callerFilePath, Int32 callerFileLine, String
memberName)
   at Microsoft.Exchange.Data.HA.DirectoryServices.ADTopologyConfigurationSessionWrapper.Find
Internal[TADWrapperObject,TADObject](ADObjectId rootId, QueryScope scope, QueryFilter
filter, SortBy sortBy, Int32 maxResults, IEnumerable`1 properties)
   at Microsoft.Exchange.Data.HA.DirectoryServices.ADTopologyConfigurationSessionWrapper.Find
[TADWrapperObject](ADObjectId rootId, QueryScope scope, QueryFilter filter, SortBy sortBy,
Int32 maxResults)
   at Microsoft.Exchange.Data.Storage.Cluster.DirectoryServices.SimpleAdObjectLookup`1.<>c__D
isplayClass9_0.<FindAdObjectTypeByGuidStatic>b__0()
   at Microsoft.Exchange.Data.Directory.ADNotificationAdapter.RunADOperation(ADOperation
adOperation, Int32 retryCount)
   at Microsoft.Exchange.Data.Directory.ADNotificationAdapter.TryRunADOperation(ADOperation
adOperation, Int32 retryCount)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Data.Storage.ActiveManager.ActiveManager.GetDatabaseByGuidEx(IFindAd
Object`1 databaseLookup, Guid databaseId, AdObjectLookupFlags flags, IPerformanceDataLogger
perfLogger)
   at
Microsoft.Exchange.Data.Storage.ActiveManager.ActiveManager.GetServerNameForDatabase(Guid
databaseId, GetServerForDatabaseFlags gsfdFlags, IPerformanceDataLogger perfLogger,
IADDatabase& database)
   at Microsoft.Exchange.Data.Storage.ActiveManager.ActiveManager.GetServerForDatabase(Guid
databaseId, GetServerForDatabaseFlags gsfdFlags, IPerformanceDataLogger perfLogger)
   at Microsoft.Exchange.Data.Storage.DatabaseLocationProvider.GetLocationInfo(Guid mdbGuid,
Boolean bypassCache, Boolean ignoreSiteBoundary)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.Data.Storage.DatabaseLocationProvider.GetLocationInfo(Guid mdbGuid,
Boolean bypassCache, Boolean ignoreSiteBoundary)
   at Microsoft.Exchange.Data.Storage.Principal.MailboxLocationFactory.Create(Guid mdbGuid,
RemotingOptions remotingOptions, Boolean createLocationOnDemand)
   at
Microsoft.Exchange.Data.Storage.ExchangePrincipalFactory.InternalFromADUser(IGenericADUser
user, RemotingOptions remotingOptions, Boolean createLocationOnDemand)
   at Microsoft.Exchange.Data.Storage.Performance.MailboxOperationPerformanceTracker.ExecuteW
ithLatencyTracking[T](ActivityOperationType operation, Func`1 action, String instance)
   at Microsoft.Exchange.Management.StoreTasks.GetMailboxRegionalConfiguration.CreateMailboxD
ataProvider(ADUser adUser)
   at Microsoft.Exchange.Configuration.Tasks.DataAccessTask`1.InternalStateReset()
   at Microsoft.Exchange.Configuration.Tasks.GetTaskBase`1.InternalStateReset()
   at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__93_1()
   at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName,
Action func, Boolean terminatePipelineIfFailed).
[Server=YTBPR01MB3038,RequestId=8be3b4cf-e565-4ceb-850a-86292a97c7d4,TimeStamp=7/11/2019
1:29:51 AM] .
    + CategoryInfo          : NotSpecified: (:) [Get-MailboxRegionalConfiguration], CmdletPr
   oxyException
    + FullyQualifiedErrorId : Microsoft.Exchange.Configuration.CmdletProxyException,Microsof
   t.Exchange.Management.StoreTasks.GetMailboxRegionalConfiguration
    + PSComputerName        : outlook.office365.com

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A (ReverseDSC Extraction)

#### The operating system the target node is running
O365DSC

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.0.0.*

**Comment by NikCharlebois** [comment]
Running same command, in a same PSSession connect with a Non-MFA account, within 2 minutes apart each:

PS C:\> Get-MailboxRegionalConfiguration -Identity:'admin'                                    Error on proxy command 'Get-MailboxRegionalConfiguration -Identity:'admin'' to server
YQBPR0101MB0851.CANPRD01.PROD.OUTLOOK.COM: Server version 15.20.2052.0000, Proxy method
PSWS:
Cmdlet error with following error message:
Microsoft.Exchange.Data.Directory.ADServerSettingsChangedException: An error caused a change
in the current set of domain controllers..
[Server=YTBPR01MB3038,RequestId=26d0693d-7c40-4f0d-a778-713d6792cabf,TimeStamp=7/11/2019
1:55:05 AM] .
    + CategoryInfo          : NotSpecified: (:) [Get-MailboxRegionalConfiguration], CmdletPr
   oxyException
    + FullyQualifiedErrorId : Microsoft.Exchange.Configuration.CmdletProxyException,Microsof
   t.Exchange.Management.StoreTasks.GetMailboxRegionalConfiguration
    + PSComputerName        : outlook.office365.com

PS C:\> Get-MailboxRegionalConfiguration -Identity:'admin'                                    
Identity             Language        DateFormat TimeFormat TimeZone
--------             --------        ---------- ---------- --------
admin                en-US           M/d/yyyy   h:mm tt    Eastern Standard Time

**Comment by NikCharlebois** [comment]
This issue doesn't seem to be occurring anymore. Closing issue
